# Copyright (C) 2021 Istituto Italiano di Tecnologia (IIT). All rights reserved.
# This software may be modified and distributed under the terms of the
# GNU Lesser General Public License v2.1 or any later version.

get_property(umbrella_includes_list GLOBAL PROPERTY umbrella_includes)
get_property(target_list GLOBAL PROPERTY KinDynVIO_TARGETS)

configure_file("${CMAKE_CURRENT_SOURCE_DIR}/cmake/KinDynVIO.h.in"
               "${CMAKE_CURRENT_BINARY_DIR}/Autogenerated/KinDynVIO/KinDynVIO.h" @ONLY)
install(FILES "${CMAKE_CURRENT_BINARY_DIR}/Autogenerated/KinDynVIO/KinDynVIO.h"
        DESTINATION "${CMAKE_INSTALL_INCLUDEDIR}/KinDynVIO")

add_library(KinDynVIO INTERFACE)
target_compile_features(KinDynVIO INTERFACE cxx_std_17)
target_link_libraries(KinDynVIO INTERFACE ${target_list})
target_include_directories(KinDynVIO INTERFACE "$<BUILD_INTERFACE:${CMAKE_CURRENT_BINARY_DIR}/Autogenerated/KinDynVIO/KinDynVIO.h>"
  "$<INSTALL_INTERFACE:$<INSTALL_PREFIX>/${CMAKE_INSTALL_INCLUDEDIR}>")
# Specify installation targets, typology and destination folders.
install(TARGETS        KinDynVIO
  EXPORT               ${PROJECT_NAME}
  COMPONENT            runtime)

add_library(KinDynVIO::KinDynVIO ALIAS KinDynVIO)
set_property(GLOBAL APPEND PROPERTY KinDynVIO_TARGETS KinDynVIO)

